# Generated by Django 3.2.6 on 2021-08-06 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bangla', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanglaEnglishRelations',
            fields=[
                ('bng_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bangla.banglawords')),
            ],
            options={
                'verbose_name_plural': 'Bangla English Relations',
            },
        ),
        migrations.CreateModel(
            name='EnglishWords',
            fields=[
                ('eng_id', models.IntegerField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=64)),
                ('bangla_word', models.ManyToManyField(through='bangla.BanglaEnglishRelations', to='bangla.BanglaWords')),
            ],
            options={
                'verbose_name_plural': 'English Words',
            },
        ),
        migrations.AddField(
            model_name='banglaenglishrelations',
            name='eng_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangla.englishwords'),
        ),
    ]
